name: Java Maven Deploy

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven deploy
      uses: qcastel/github-actions-maven-release@v1.0.3
      with:
        # Filter the branch to execute the release on
        release-branch-name: "master"
        # Enable gpg signing
        #gpg-enabled: "true"
        # The GPG key ID
        #gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
        # The GPG key
        #gpg-key: ${{ secrets.GITHUB_GPG_KEY }}
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@example.com"
        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
